/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.6.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as confirmUserIdentity from "../confirmUserIdentity";
import type * as createGame from "../createGame";
import type * as destroyGame from "../destroyGame";
import type * as getGame from "../getGame";
import type * as listGames from "../listGames";
import type * as listUsers from "../listUsers";
import type * as storeUser from "../storeUser";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  confirmUserIdentity: typeof confirmUserIdentity;
  createGame: typeof createGame;
  destroyGame: typeof destroyGame;
  getGame: typeof getGame;
  listGames: typeof listGames;
  listUsers: typeof listUsers;
  storeUser: typeof storeUser;
}>;
